### PR TITLE
Version 1.1

### PR DESCRIPTION
**Pull request by cmaloney111**
code adapts to all browser sizes

### CODE REVIEW

**Comment by SanJuanse9000** [comment]
I LIKE THIS

**Comment by SanJuanse9000** [comment]
LIKE MIKE AND IKE

**Comment by SanJuanse9000** [comment]
YOU ARE AWESOME

**Comment by SanJuanse9000** [comment]
BUT NOT AS MUCH AS SAN JUANSE

**Comment by cmaloney111** [comment]
thanks

**Pull request merged**
